use_frameworks!

platform :ios, '10.0'

target 'PTDebugView_Example' do
  pod 'PTDebugView', :path => '../'

  target 'PTDebugView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
